arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    shoulder_pan_joint: { p: 100.0, d: 1.0, i: 1.0, i_clamp: 1.0 }
    shoulder_lift_joint: { p: 100.0, d: 1.0, i: 1.0, i_clamp: 1.0 }
    elbow_joint: { p: 100.0, d: 1.0, i: 1.0, i_clamp: 1.0 }
    wrist_1_joint: { p: 100.0, d: 1.0, i: 1.0, i_clamp: 1.0 }
    wrist_2_joint: { p: 100.0, d: 1.0, i: 1.0, i_clamp: 1.0 }
    wrist_3_joint: { p: 100.0, d: 1.0, i: 1.0, i_clamp: 1.0 }

