trajectory_execution:
  moveit_manage_controllers: true
  execution_duration_monitoring: false
  allowed_start_tolerance: 0.01
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
